baseURL: https://cclhm0057.netlify.app/
title: "PPGCS012 - Ciência Social Computacional - 2021.2 "
theme: hugo-theme-zdoc
description: "Curso PPGCS012 - Ciência Social Computacional, no âmbito do programa de pós-graduação em Ciências Sociais da UFBA, ministrado por Leonardo Fernandes (ICTI/UFBA) e Eric Brasil (IHLM/UNILBA) no semestre 2021.2."
defaultContentLanguage: pt
defaultContentLanguageInSubdir: no
hasCJKLanguage: no
copyright: "Conteúdo original criado por Leonardo Nascimento e Eric Brasil sob licença <a rel='license' href='http://creativecommons.org/licenses/by-nc/4.0/'>Creative Commons Attribution-NonCommercial 4.0 International License</a><br><a rel='license' href='http://creativecommons.org/licenses/by-nc/4.0/'><img alt='Creative Commons License logo' style='border-width:0' src='https://i.creativecommons.org/l/by-nc/4.0/88x31.png' /></a>"
timeout: 10000
enableEmoji: yes
paginate: 13
rssLimit: 100
googleAnalytics: ''
disableKinds: taxonomyTerm
markup:
  goldmark:
    renderer:
      hardWraps: yes
      unsafe: yes
      xHTML: yes
  highlight:
    codeFences: yes
    lineNos: yes
    lineNumbersInTable: yes
    noClasses: no
  tableOfContents:
    endLevel: 4
    ordered: no
    startLevel: 2
outputs:
  home:
    - HTML
    - RSS
    - SearchIndex
outputFormats:
  SearchIndex:
    baseName: index
    isPlainText: yes
    mediaType: application/json
    notAlternative: yes
taxonomies:
  tag: tags
